app/cine/views.py
from http import HTTPStatus
from flask import Blueprint, request, render_template, url_for, redirect
from app.cine.models import crear_cine, get_cines, eliminar_cine, modificar_cine, cine_por_id
from app.ciudad.models import get_ciudades
import copy
from flask_login import login_required

RESPONSE_BODY_DEFAULT = {"message": "", "data": [], "errors": []}
cine = Blueprint("cine", __name__, url_prefix="/cine")

@cine.route("/template", methods=["GET"])
@login_required
def template():
    cines = get_cines()
    return render_template("cine/index.html", cines = cines)

@cine.route("/agregar", methods=["POST","GET"])
@login_required
def agregar():
    response_body = copy.deepcopy(RESPONSE_BODY_DEFAULT)
    status_code = HTTPStatus.OK
    if request.method == "POST":
        if not "cin_v_nombre" in request.json: 
            response_body["errors"].append("Campo nombre es requerido")
            status_code = HTTPStatus.BAD_REQUEST
            return response_body, status_code  
        if not "cin_fk_ciu" in request.json:
            response_body["errors"].append("Debe escoger una ciudad")
            status_code = HTTPStatus.BAD_REQUEST
            return response_body, status_code   

        cin_v_nombre = request.json["cin_v_nombre"]
        cin_fk_ciu = request.json["cin_fk_ciu"]

        if cin_v_nombre == "":
            response_body["errors"].append("Campo nombre es requerido")
            status_code = HTTPStatus.BAD_REQUEST
            return response_body, status_code
        if cin_fk_ciu == "":
            response_body["errors"].append("Debe escoger una ciudad")
            status_code = HTTPStatus.BAD_REQUEST
            return response_body, status_code
        else:
            cine = crear_cine(cin_v_nombre, cin_fk_ciu)
            response_body["data"] = {"cine": cine, "redirect": url_for('cine.template')}
            response_body["message"] = "Cine creado correctamente"
        return response_body, status_code
    else:
        ciudades = get_ciudades()
        return render_template('cine/agregar.html', ciudades = ciudades)

@cine.route("/editar/<id_cine>", methods=["POST","GET"])
@login_required
def editar(id_cine):
    response_body = copy.deepcopy(RESPONSE_BODY_DEFAULT)
    status_code = HTTPStatus.OK
    if request.method == "POST":
        if not "cin_v_nombre" in request.json: 
            response_body["errors"].append("Campo nombre es requerido")
            status_code = HTTPStatus.BAD_REQUEST
            return response_body, status_code

        cin_v_nombre = request.json["cin_v_nombre"]
        if cin_v_nombre == "":
            response_body["errors"].append("Campo nombre es requerido")
            status_code = HTTPStatus.BAD_REQUEST
            return response_body, status_code
        else:
            cine = modificar_cine(id_cine, cin_v_nombre)
            response_body["data"] = {"cine": cine, "redirect": url_for('cine.template')}
            response_body["message"] = "Cine editado correctamente"
        return response_body, status_code
    else:
        cine = cine_por_id(id_cine)
        return render_template('cine/editar.html', cine = cine)

@cine.route("/quitar/<id_cine>", methods=["GET"])
@login_required
def quitar(id_cine):
    response_body = copy.deepcopy(RESPONSE_BODY_DEFAULT)
    status_code = HTTPStatus.OK
    if eliminar_cine(id_cine):
        response_body["data"] = {"cine": cine, "redirect": url_for('cine.template')}
        response_body["message"] = "Cine eliminado correctamente"
    else:
        response_body["errors"].append("El cine no existe")
        status_code = HTTPStatus.BAD_REQUEST

    return redirect(url_for('cine.template'))

@cine.route("/", methods=["GET"])
def index():
    response_body = copy.deepcopy(RESPONSE_BODY_DEFAULT)
    status_code = HTTPStatus.OK
    cines = get_cines()
    response_body["message"] = "Cines consultados correctamente!"
    response_body["data"] = cines
    return response_body, status_code

@cine.route("/crear", methods=["POST"])
def crear():
    response_body = copy.deepcopy(RESPONSE_BODY_DEFAULT)
    status_code = HTTPStatus.OK
    cin_v_nombre = request.json["cin_v_nombre"]
    cin_fk_ciu = request.json["cin_fk_ciu"]

    if cin_v_nombre != "" and cin_v_nombre != None:
        if cin_fk_ciu != "" and cin_fk_ciu != None:
            cine = crear_cine(cin_v_nombre, cin_fk_ciu)

            response_body["message"] = "Cine creado correctamente!"
            response_body["data"] = cine
        else:
            response_body["errors"].append("Nombre vacio")
            status_code = HTTPStatus.BAD_REQUEST
    else:
        response_body["errors"].append("fk vacia")
        status_code = HTTPStatus.BAD_REQUEST
    
    return response_body, status_code

@cine.route("/modificar", methods=["PUT"])
def modificar():
    response_body = copy.deepcopy(RESPONSE_BODY_DEFAULT)
    status_code = HTTPStatus.OK

    cin_i_id = request.json["cin_i_id"]
    cin_v_nombre = request.json["cin_v_nombre"]
    
    if cin_i_id != "" and cin_i_id != None:
        if cin_v_nombre != "" and cin_v_nombre != None:
            cine_mod = modificar_cine(cin_i_id, cin_v_nombre)
            if cine_mod != None:
                response_body["message"] = "Cine modificado correctamente!"
                response_body["data"] = cine_mod
            else:
                response_body["message"] = "No se encontro el cine"
                response_body["errors"].append("Error al modificar cine")
                status_code = HTTPStatus.BAD_REQUEST
        else:
            response_body["message"] = "Nombre vacio"
            response_body["errors"].append("Error al modificar cine")
            status_code = HTTPStatus.BAD_REQUEST
    else:
        response_body["message"] = "ID vacio"
        response_body["errors"].append("Error al modificar cine")
        status_code = HTTPStatus.BAD_REQUEST

    return response_body, status_code
    
@cine.route("/eliminar", methods=["DELETE"])
def eliminar():
    response_body = copy.deepcopy(RESPONSE_BODY_DEFAULT)
    status_code = HTTPStatus.OK

    cin_i_id = request.json["cin_i_id"]

    if cin_i_id != "" and cin_i_id != None:
        if eliminar_cine(cin_i_id):
            response_body["message"] = "Cine eliminado correctamente!"
        else:
            response_body["message"] = "Error no se encuentra el cine"
            response_body["errors"].append("Error al eliminar el cine")
            status_code = HTTPStatus.BAD_REQUEST
    else:
        response_body["message"] = "Id vacio"
        response_body["errors"].append("Error al eliminar el cine")
        status_code = HTTPStatus.BAD_REQUEST
    
    return response_body, status_code

app/pelicula/views.py
from datetime import datetime
from http import HTTPStatus
from flask import Blueprint, render_template, url_for, redirect, request
from flask_login import login_required
from app.actor.models import obtener_actores
from app.pelicula.models import obtener_generos, crear_pelicula, crear_genero, crear_pelicula_genero, \
    crear_pelicula_actor, obtener_peliculas, obtener_pelicula_por_id, modificar_pelicula, eliminar_pelicula_genero, \
    eliminar_pelicula_actor, obtener_actores_por_pelicula, obtener_generos_por_pelicula, cuenta_funciones_por_pelicula, \
    eliminar_pelicula, obtener_peliculas_en_cartelera_por_ciudad, obtener_peliculas_mas_vistas_por_ciudad, \
    obtener_peliculas_por_estado, generos_por_cliente
import copy
import base64
import uuid
import json

pelicula = Blueprint("pelicula", __name__, url_prefix="/pelicula")

RESPONSE_BODY_DEFAULT = {"message": "", "data": [], "errors": [], "metadata": []}
BASE_PATH = "app/static/peliculas/"

@pelicula.route("/", methods=["GET"])
@login_required
def index():
    peliculas = obtener_peliculas()
    data = {
        "peliculas":peliculas
    }
    return render_template('pelicula/index.html', data=data)


@pelicula.route("/agregar", methods=["POST","GET"])
@login_required
def agregar():
    response_body = copy.deepcopy(RESPONSE_BODY_DEFAULT)
    status_code = HTTPStatus.OK
    if request.method == "POST":



        if not "pel_v_titulo" in request.json:
            response_body["errors"].append("Campo titulo es requerido")
            status_code = HTTPStatus.BAD_REQUEST
            return response_body, status_code
        if not "pel_t_sinopsis" in request.json:
            response_body["errors"].append("Campo sinopsis es requerido")
            status_code = HTTPStatus.BAD_REQUEST
            return response_body, status_code
        if not "pel_v_director" in request.json:
            response_body["errors"].append("Campo director es requerido")
            status_code = HTTPStatus.BAD_REQUEST
            return response_body, status_code
        if not "pel_i_duracion" in request.json:
            response_body["errors"].append("Campo duracion es requerido")
            status_code = HTTPStatus.BAD_REQUEST
            return response_body, status_code
        if not "pel_d_estreno" in request.json:
            response_body["errors"].append("Campo estreno es requerido")
            status_code = HTTPStatus.BAD_REQUEST
            return response_body, status_code
        if not "pel_v_ruta_poster_data" in request.json:
            response_body["errors"].append("Campo poster es requerido")
            status_code = HTTPStatus.BAD_REQUEST
            return response_body, status_code
        if not "pel_v_ruta_banner_data" in request.json:
            response_body["errors"].append("Campo banner es requerido")
            status_code = HTTPStatus.BAD_REQUEST
            return response_body, status_code
        if not "pel_v_pais_origen" in request.json:
            response_body["errors"].append("Campo pais origen es requerido")
            status_code = HTTPStatus.BAD_REQUEST
            return response_body, status_code
        if not "pel_i_edad_minima" in request.json:
            response_body["errors"].append("Campo edad minima es requerido")
            status_code = HTTPStatus.BAD_REQUEST
            return response_body, status_code
        if not "pel_i_estado" in request.json:
            response_body["errors"].append("Campo estado película es requerido")
            status_code = HTTPStatus.BAD_REQUEST
            return response_body, status_code

        pel_v_titulo = request.json["pel_v_titulo"]
        pel_t_sinopsis = request.json["pel_t_sinopsis"]
        pel_v_director = request.json["pel_v_director"]
        pel_i_duracion = request.json["pel_i_duracion"]
        pel_d_estreno = request.json["pel_d_estreno"]
        pel_v_ruta_poster = request.json["pel_v_ruta_poster_data"]
        pel_v_ruta_banner = request.json["pel_v_ruta_banner_data"]
        pel_v_pais_origen = request.json["pel_v_pais_origen"]
        pel_i_edad_minima = request.json["pel_i_edad_minima"]
        pel_i_estado = request.json["pel_i_estado"]


        if pel_v_titulo == "":
            response_body["errors"].append("Campo titulo es requerido")
            status_code = HTTPStatus.BAD_REQUEST
            return response_body, status_code
        if pel_t_sinopsis == "":
            response_body["errors"].append("Campo sinopsis es requerido")
            status_code = HTTPStatus.BAD_REQUEST
            return response_body, status_code
        if pel_v_director == "":
            response_body["errors"].append("Campo director es requerido")
            status_code = HTTPStatus.BAD_REQUEST
            return response_body, status_code
        if pel_i_duracion == "":
            response_body["errors"].append("Campo duracion es requerido")
            status_code = HTTPStatus.BAD_REQUEST
            return response_body, status_code
        if pel_d_estreno == "":
            response_body["errors"].append("Campo estreno es requerido")
            status_code = HTTPStatus.BAD_REQUEST
            return response_body, status_code
        if pel_v_ruta_poster == "":
            response_body["errors"].append("Campo poster es requerido")
            status_code = HTTPStatus.BAD_REQUEST
            return response_body, status_code
        if pel_v_ruta_banner == "":
            response_body["errors"].append("Campo banner es requerido")
            status_code = HTTPStatus.BAD_REQUEST
            return response_body, status_code
        if pel_v_pais_origen == "":
            response_body["errors"].append("Campo pais origen es requerido")
            status_code = HTTPStatus.BAD_REQUEST
            return response_body, status_code
        if pel_i_edad_minima == "":
            response_body["errors"].append("Campo edad minima es requerido")
            status_code = HTTPStatus.BAD_REQUEST
            return response_body, status_code
        if pel_i_estado == "":
            response_body["errors"].append("Campo estado película es requerido")
            status_code = HTTPStatus.BAD_REQUEST
            return response_body, status_code



        pel_v_ruta_poster = pel_v_ruta_poster.replace(" ","+")
        base64Data = pel_v_ruta_poster.split(",")

        extension = ".txt"
        if "jpeg" in base64Data[0]:
            extension = ".jpg"
        elif "png" in base64Data[0]:
            extension = ".png"

        ruta_poster = str(uuid.uuid4())+ extension

        pel_v_ruta_poster = base64Data[1]
        try:
            with open(BASE_PATH + ruta_poster, "wb") as fh:
                fh.write(base64.urlsafe_b64decode(pel_v_ruta_poster))
        except BaseException as e:
           print(str(e))


        pel_v_ruta_banner = pel_v_ruta_banner.replace(" ","+")
        base64Data = pel_v_ruta_banner.split(",")
        extension = ".txt"
        if "jpeg" in base64Data[0]:
            extension = ".jpg"
        elif "png" in base64Data[0]:
            extension = ".png"

        ruta_banner = str(uuid.uuid4())+ extension
        pel_v_ruta_banner = base64Data[1]
        try:
            with open(BASE_PATH + ruta_banner, "wb") as fh:
                fh.write(base64.urlsafe_b64decode(pel_v_ruta_banner))
        except BaseException as e:
           print(str(e))

        fecha_estreno = datetime.strptime(pel_d_estreno, '%Y-%m-%d')

        pelicula = crear_pelicula(pel_v_titulo, pel_t_sinopsis, pel_v_director,
                                  pel_i_duracion, fecha_estreno, ruta_poster,
                                  ruta_banner, pel_v_pais_origen, pel_i_edad_minima, pel_i_estado)

        num_generos = int(request.json["num_generos"])
        for n_genero in range(1,num_generos + 1):
            if "genero_" + str(n_genero) in request.json:
                genero_json = request.json["genero_" + str(n_genero)]
                if genero_json == "otro":
                    genero = crear_genero(request.json["otro_genero_" + str(n_genero)])
                    genero_json = genero["gen_i_id"]
                crear_pelicula_genero(pelicula["pel_i_id"], genero_json)

        num_actores = int(request.json["num_actores"])
        for n_actor in range(1,num_actores + 1):
            if "actor_" + str(n_actor) in request.json:
                actor_json = request.json["actor_" + str(n_actor)]
                crear_pelicula_actor(pelicula["pel_i_id"], actor_json)







        response_body["data"] = {"pel_v_titulo": pel_v_titulo, "redirect": url_for('pelicula.index')}
        response_body["message"] = "Se agregó la película"
        return response_body, status_code
    else:
        generos = obtener_generos()
        actores = obtener_actores()

        data = {
            "generos":generos,
            "actores":actores
        }

        return render_template('pelicula/agregar.html', data=data)


@pelicula.route("/select_generos/<int:num>", methods=["GET"])
@login_required
def select_generos(num):
    response_body = copy.deepcopy(RESPONSE_BODY_DEFAULT)
    status_code = HTTPStatus.OK
    num = str(num)
    elemento = '<div class="col-md-3 generos">' \
    '<div class="form-floating">'\
    '<select class="form-control form-select select-otro" id="genero_'+num+'" name="genero_'+num+'" required="" data-otro="otro_genero_'+num+'" >' \
    '<option selected  value="">Seleccione uno</option>'
    generos = obtener_generos()
    for genero in generos:
        print(generos)
        elemento += '<option value="'+str(genero["gen_i_id"])+'">'+genero["gen_v_nombre"]+'</option>'

    elemento += '<option value="otro">Otro</option>' \
    '</select>' \
    '<label for="genero_'+num+'">Genero '+num+'</label>' \
    '<div class="form-floating otro">' \
    '<input autocomplete="off" type="text" class="form-control " id="otro_genero_'+num+'" name="otro_genero_'+num+'" placeholder="Otro Genero '+num+'" value="">' \

app/templates/pelicula/agregar.html
{% extends "baseLogueado.html" %}
{% block title %} Peliculas {% endblock %}
{% block head %}
    {{ super() }}
{% endblock %}
{% block contenido %}
    <div class="container">
        <div class="row">
            <div class="col-12">
                <nav aria-label="breadcrumb">
                  <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="{{url_for('pelicula.index')}}">Pel&iacute;culas</a></li>
                        <li class="breadcrumb-item active" aria-current="page">Agregar</li>
                  </ol>
                </nav>
            </div>
        </div>
        <h1>Agregar pel&iacute;cula</h1>
        <div class="row">
            <div class="col-12">
                <form action="{{url_for('pelicula.agregar')}}" method="post" class="formulario-general">
                    <div class="row">
                        <div class="col-3">
                            <div class="form-floating">
                                <input type="text" class="form-control" id="pel_v_titulo" required name="pel_v_titulo" placeholder="T&iacute;tulo">
                                <label for="pel_v_titulo">T&iacute;tulo</label>
                            </div>
                        </div>
                        <div class="col-3">
                            <div class="form-floating">
                                <input type="text" class="form-control" id="pel_v_director" name="pel_v_director" placeholder="Director">
                                <label for="pel_v_director">Director</label>
                            </div>
                        </div>
                        <div class="col-3">
                            <div class="form-floating">
                                <input type="number" class="form-control" id="pel_i_duracion" name="pel_i_duracion" placeholder="Duraci&oacute;n (min)">
                                <label for="pel_i_duracion">Duraci&oacute;n (min)</label>
                            </div>
                        </div>
                        <div class="col-3">
                            <div class="form-floating">
                                <input type="date" class="form-control" id="pel_d_estreno" name="pel_d_estreno" placeholder="Fecha de estreno">
                                <label for="pel_d_estreno">Fecha de estreno</label>
                            </div>
                        </div>
                        <div class="col-3">
                            <div class="form-floating">
                                <input type="text" class="form-control" id="pel_v_pais_origen" name="pel_v_pais_origen" placeholder="Pais origen">
                                <label for="pel_v_pais_origen">Pais origen</label>
                            </div>
                        </div>
                        <div class="col-3">
                            <div class="form-floating">
                                <input type="number" min="0" class="form-control" id="pel_i_edad_minima" name="pel_i_edad_minima" placeholder="Edad minima">
                                <label for="pel_i_edad_minima">Edad minima</label>
                            </div>
                        </div>
                        <div class="col-3">
                            <div class="form-floating">
                                <select class="form-control form-select" id="pel_i_estado" name="pel_i_estado" required="">
                                    <option value="">Seleccione uno</option>
                                    <option value="1">En cartelera</option>
                                    <option value="2">En estreno</option>
                                    <option value="3">Fuera de cartelera</option>
                                 </select>
                                <label for="pel_i_estado">Estado </label>
                            </div>
                        </div>
                    </div>
                    <div class="row" id="cont_generos">
                        <div class="col-3">
                            <div class="row align-items-center" style="margin-bottom: 1.5em;">
                                <div class="col-md-4 text-right"><label for="num_generos">Generos</label></div>
                                <div class="col-md-2 text-center">
                                    <a href="#" id="menos_gen" class="a-gris"><i class="far fa-minus-square"></i></a>
                                </div>
                                <div class="col-md-4 text-center">
                                    <input type="text" class="form-control nums" name="num_generos" id="num_generos" value="1">
                                </div>
                                <div class="col-md-2 text-center">
                                    <a href="#" id="mas_gen"  class="a-rosa"><i class="far fa-plus-square"></i></a>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-3 generos">
                            <div class="form-floating">
                                <select class="form-control form-select select-otro" id="genero_1" name="genero_1" required="" data-otro="otro_genero_1" >
                                    <option selected value="">Seleccione uno</option>
                                    {% for genero in data.generos %}
                                        <option value="{{ genero.gen_i_id }}">{{genero.gen_v_nombre}}</option>
                                    {% endfor %}
                                    <option value="otro">Otro</option>
                                 </select>
                                <label for="genero_1">Genero 1</label>
                                <div class="form-floating otro">
                                    <input autocomplete="off" type="text" class="form-control " id="otro_genero_1" name="otro_genero_1" placeholder="Otro Genero 1" value="">
                                    <label for="otro_genero_1">Otro Genero 1</label>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row" id="cont_actores">
                        <div class="col-3">
                            <div class="row align-items-center" style="margin-bottom: 1.5em;">
                                <div class="col-md-4 text-right"><label for="num_actores">Actores</label></div>
                                <div class="col-md-2 text-center">
                                    <a href="#" id="menos_act" class="a-gris"><i class="far fa-minus-square"></i></a>
                                </div>
                                <div class="col-md-4 text-center">
                                    <input type="text" class="form-control nums" name="num_actores" id="num_actores" value="1">
                                </div>
                                <div class="col-md-2 text-center">
                                    <a href="#" id="mas_act"  class="a-rosa"><i class="far fa-plus-square"></i></a>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-3 actores">
                            <div class="form-floating">
                                <select class="form-control form-select" id="actor_1" name="actor_1" required="" >
                                    <option selected value="">Seleccione uno</option>
                                    {% for actor in data.actores %}
                                        <option value="{{ actor.act_i_id }}">{{actor.act_v_nombre}} {{actor.act_v_apellido}}</option>
                                    {% endfor %}
                                 </select>
                                <label for="actor_1">Actor 1</label>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-12">
                            <div class="form-floating">
                              <textarea class="form-control" placeholder="Sinopsis" id="pel_t_sinopsis" name="pel_t_sinopsis" style="height: 100px"></textarea>
                              <label for="pel_t_sinopsis">Sinopsis</label>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-12">
                            <label for="pel_v_ruta_poster" class="upload-box-label">Foto poster</label>
                            <div class="upload-box " id="box" data-input="pel_v_ruta_poster" data-input-data="pel_v_ruta_poster_data" data-preview="preview">
                                    <img src="{{url_for('static', filename='imgs/drag_file.png')}}"><br>
                                    Arrastra la foto<br>
                                    o<br>
                                <button type="button" class="upload-btn" data-input="pel_v_ruta_poster">
                                    <img src="{{url_for('static', filename='imgs/upload.png')}}"> Seleccionar imagen
                                </button>
                                <input autocomplete="off" accept="image/*" type="file" id="pel_v_ruta_poster">
                                <input autocomplete="off" type="hidden" name="pel_v_ruta_poster_data" id="pel_v_ruta_poster_data">
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-12 col-preview">
                            <label for="preview">Vista previa poster</label><br>
                            <img src="{{url_for('static', filename='imgs/no-image.png')}}" id="preview">
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-12">
                            <label for="pel_v_ruta_banner" class="upload-box-label">Banner</label>
                            <div class="upload-box " id="box_banner" data-input="pel_v_ruta_banner" data-input-data="pel_v_ruta_banner_data" data-preview="preview_banner">
                                    <img src="{{url_for('static', filename='imgs/drag_file.png')}}"><br>
                                    Arrastra la foto<br>
                                    o<br>
                                <button type="button" class="upload-btn" data-input="pel_v_ruta_banner">
                                    <img src="{{url_for('static', filename='imgs/upload.png')}}"> Seleccionar imagen
                                </button>
                                <input autocomplete="off" accept="image/*" type="file" id="pel_v_ruta_banner">
                                <input autocomplete="off" type="hidden" name="pel_v_ruta_banner_data" id="pel_v_ruta_banner_data">
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-12 col-preview">
                            <label for="preview_banner">Vista previa banner</label><br>
                            <img src="{{url_for('static', filename='imgs/no-image.png')}}" id="preview_banner">
                        </div>
                    </div>


                    <div class="row">
                        <div class="offset-5 col-2">
                            <button class="btn btn-gen">Enviar</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}
{% block scripts %}
<script src="{{ url_for('static', filename='js/formulario_general.js')}}"></script>
<script src="{{ url_for('static', filename='js/formulario_peliculas.js')}}"></script>
{% endblock %}

app/templates/pelicula/index.html
{% extends "baseLogueado.html" %}
{% block title %} Peliculas {% endblock %}
{% block head %}
    {{ super() }}
{% endblock %}
{% block contenido %}
    <div class="container">
        <div class="row">
            <div class="col-12">
                <nav aria-label="breadcrumb">
                  <ol class="breadcrumb">
                    <li class="breadcrumb-item active" aria-current="page">Peliculas</li>
                  </ol>
                </nav>
            </div>
        </div>
        <div class="row">
            <div class="offset-9 col-3 text-end">
                <a class="btn btn-gen" href="{{url_for('pelicula.agregar')}}">Agregar pelicula</a>
            </div>
        </div>

        <div class="card-deck">
            {% for pelicula in data.peliculas %}
            <div class="card">
                <img class="card-img-top" src="{{ url_for('static', filename='peliculas/'+pelicula.pel_v_ruta_poster)}}">
                <div class="card-body">
                    <h5 class="card-title">{{ pelicula.pel_v_titulo }}</h5>
                    <p class="card-text">
                        {% if(pelicula.pel_t_sinopsis|length) > 50 %}
                            {{  pelicula.pel_t_sinopsis[0:50] }} ...
                        {% else %}
                            {{ pelicula.pel_t_sinopsis }}
                        {% endif %}
                    </p>


                </div>
                <div class="card-footer card-buttons">
                    <a href="{{url_for('pelicula.modificar', id=pelicula.pel_i_id)}}" class="btn btn-gen">Editar</a>
                    <a href="{{url_for('pelicula.eliminar',id=pelicula.pel_i_id)}}" class="btn btn-secondary eliminar" data-msj="esta película">Eliminar</a>
                </div>
            </div>

            {% endfor %}
        </div>

    </div>
{% endblock %}
{% block scripts %}
<script src="{{ url_for('static', filename='js/lista_general.js')}}"></script>
{% endblock %}