app/actor/models.py
from app.db import db, ma


class Actor(db.Model):
    act_i_id = db.Column(db.Integer, primary_key=True)
    act_v_nombre = db.Column(db.String(45), nullable=False)
    act_v_apellido = db.Column(db.String(45), nullable=False)

class ActorSchema(ma.SQLAlchemyAutoSchema):
    class Meta:
        model = Actor
        fields = ["act_i_id", "act_v_nombre", "act_v_apellido"]


def obtener_actores():
    actores = Actor.query.all()
    actor_schema = ActorSchema()
    actores = [actor_schema.dump(actor) for actor in actores]
    return actores


def obtener_actor_por_id(act_i_id):
    actor = Actor.query.filter_by(act_i_id=act_i_id).first()
    if actor != None:
        actor_schema = ActorSchema()
        actor = actor_schema.dump(actor)
        return actor
    else:
        return None



def crear_actor(nombre, apellido):
    actor = Actor(act_v_nombre=nombre, act_v_apellido=apellido)
    db.session.add(actor)
    db.session.commit()
    actor_schema = ActorSchema()
    return actor_schema.dump(actor)


def eliminar_actor(id):
    actor = Actor.query.filter_by(act_i_id=id).first()
    if actor != None:
        Actor.query.filter_by(act_i_id=id).delete()
        db.session.commit()
        return True
    else:
        return False


def modificar_actor(id, nombre, apellido):
    actor = Actor.query.filter_by(act_i_id=id).first()
    if actor != None:
        actor.act_v_nombre = nombre
        actor.act_v_apellido = apellido
        db.session.commit()
        actor_schema = ActorSchema()
        return actor_schema.dump(actor)
    return None

app/actor/views.py
from http import HTTPStatus

from flask import Blueprint, render_template, url_for, redirect, request
from flask_login import login_required
import copy

from app.actor.models import obtener_actores, crear_actor, eliminar_actor, obtener_actor_por_id, modificar_actor
from app.pelicula.models import cuenta_peliculas_por_actor

actor = Blueprint("actor", __name__, url_prefix="/actor")

RESPONSE_BODY_DEFAULT = {"message": "", "data": [], "errors": [], "metadata": []}


@actor.route("/", methods=["GET"])
@login_required
def index():
    actores = obtener_actores()
    data = {
        "actores":actores
    }
    return render_template('actor/index.html', data=data)


@actor.route("/agregar", methods=["POST","GET"])
@login_required
def agregar():
    response_body = copy.deepcopy(RESPONSE_BODY_DEFAULT)
    status_code = HTTPStatus.OK
    if request.method == "POST":

        if not "act_v_nombre" in request.json:
            response_body["errors"].append("Campo nombre es requerido")
            status_code = HTTPStatus.BAD_REQUEST
            return response_body, status_code

        if not "act_v_apellido" in request.json:
            response_body["errors"].append("Campo apellido es requerido")
            status_code = HTTPStatus.BAD_REQUEST
            return response_body, status_code



        act_v_nombre = request.json["act_v_nombre"]
        act_v_apellido = request.json["act_v_apellido"]


        if act_v_nombre == "":
            response_body["errors"].append("Campo nombre es requerido")
            status_code = HTTPStatus.BAD_REQUEST
            return response_body, status_code

        if act_v_apellido == "":
            response_body["errors"].append("Campo apellido es requerido")
            status_code = HTTPStatus.BAD_REQUEST
            return response_body, status_code

        actor = crear_actor(act_v_nombre, act_v_apellido)


        response_body["data"] = {"redirect": url_for('actor.index')}
        response_body["message"] = "Se agregó el actor"
        return response_body, status_code
    else:

        return render_template('actor/agregar.html')


@actor.route("/eliminar/<int:id>", methods=["GET"])
@login_required
def eliminar(id):
    response_body = copy.deepcopy(RESPONSE_BODY_DEFAULT)
    status_code = HTTPStatus.BAD_REQUEST
    if id != "":

        if cuenta_peliculas_por_actor(id) > 0:
            response_body["errors"].append("Error el actor tiene películas relacionadas")
            return response_body, status_code

        if eliminar_actor(id):
            return redirect(url_for('actor.index'))
        else:
            response_body["errors"].append("Error al eliminar el actor")
            return response_body, status_code

    else:
        response_body["errors"].append("El id es requerido, para eliminar el actor")
        return response_body, status_code


@actor.route("/modificar/<int:id>", methods=["POST","GET"])
@login_required
def modificar(id):
    response_body = copy.deepcopy(RESPONSE_BODY_DEFAULT)
    status_code = HTTPStatus.OK
    if request.method == "POST":
        if not "act_v_nombre" in request.json:
            response_body["errors"].append("Campo nombre es requerido")
            status_code = HTTPStatus.BAD_REQUEST
            return response_body, status_code

        if not "act_v_apellido" in request.json:
            response_body["errors"].append("Campo apellido es requerido")
            status_code = HTTPStatus.BAD_REQUEST
            return response_body, status_code

        act_v_nombre = request.json["act_v_nombre"]
        act_v_apellido = request.json["act_v_apellido"]


        if act_v_nombre == "":
            response_body["errors"].append("Campo nombre es requerido")
            status_code = HTTPStatus.BAD_REQUEST
            return response_body, status_code

        if act_v_apellido == "":
            response_body["errors"].append("Campo apellido es requerido")
            status_code = HTTPStatus.BAD_REQUEST
            return response_body, status_code

        actor = modificar_actor(id,act_v_nombre, act_v_apellido)
        response_body["data"] = {"redirect": url_for('actor.index')}
        response_body["message"] = "Se modificó el actor"
        return response_body, status_code

    else:
        actor = obtener_actor_por_id(id)
        if actor is None:
            return redirect('actor.index')
        else:
            data = {
                "actor":actor
            }
            return render_template('actor/modificar.html', data=data)

app/templates/actor/agregar.html
{% extends "baseLogueado.html" %}
{% block title %} Actor {% endblock %}
{% block head %}
    {{ super() }}
{% endblock %}
{% block contenido %}
    <div class="container">
        <div class="row">
            <div class="col-12">
                <nav aria-label="breadcrumb">
                  <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="{{url_for('actor.index')}}">Actores</a></li>
                        <li class="breadcrumb-item active" aria-current="page">Agregar</li>
                  </ol>
                </nav>
            </div>
        </div>
        <h1>Agregar actor</h1>
        <div class="row">
            <div class="col-12">
                <form action="{{url_for('actor.agregar')}}" method="post" class="formulario-general">
                    <div class="row">
                        <div class="col-3">
                            <div class="form-floating">
                                <input type="text" class="form-control" id="act_v_nombre" name="act_v_nombre" placeholder="Nombre">
                                <label for="act_v_nombre">Nombre</label>
                            </div>
                        </div>
                        <div class="col-3">
                            <div class="form-floating">
                                <input type="text" class="form-control" id="act_v_apellido" name="act_v_apellido" placeholder="Apellido">
                                <label for="act_v_apellido">Apellido</label>
                            </div>
                        </div>
                    </div>

                    <div class="row">
                        <div class="offset-5 col-2">
                            <button class="btn btn-gen">Enviar</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}
{% block scripts %}
<script src="{{ url_for('static', filename='js/formulario_general.js')}}"></script>
{% endblock %}

app/templates/actor/index.html
{% extends "baseLogueado.html" %}
{% block title %} Actor {% endblock %}
{% block head %}
    {{ super() }}
{% endblock %}
{% block contenido %}
    <div class="container">
        <div class="row">
            <div class="col-12">
                <nav aria-label="breadcrumb">
                  <ol class="breadcrumb">
                    <li class="breadcrumb-item active" aria-current="page">Actores</li>
                  </ol>
                </nav>
            </div>
        </div>
        <div class="row">
            <div class="offset-9 col-3 text-end">
                <a class="btn btn-gen" href="{{url_for('actor.agregar')}}">Agregar actor</a>
            </div>
        </div>

        <table class="table table-hover table-striped">
            <thead>
                <tr>
                    <th scope="col">Nombre</th>
                    <th scope="col">Apellido</th>
                    <th scope="col">Editar</th>
                    <th scope="col">Eliminar</th>
                </tr>
            </thead>
            <tbody>
                {% for actor in data.actores %}
                <tr>
                    <td>{{actor.act_v_nombre}}</td>
                    <td>{{actor.act_v_apellido}}</td>
                    <td><a href="{{url_for('actor.modificar',id=actor.act_i_id)}}" class="a-rosa"><i class="far fa-edit"></i></a></td>
                    <td><a href="{{url_for('actor.eliminar',id=actor.act_i_id)}}" class="a-rosa eliminar" data-msj="este actor"><i class="fas fa-trash-alt"></i></a></td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}
{% block scripts %}
<script src="{{ url_for('static', filename='js/lista_general.js')}}"></script>
{% endblock %}

app/templates/actor/modificar.html
{% extends "baseLogueado.html" %}
{% block title %} Actor {% endblock %}
{% block head %}
    {{ super() }}
{% endblock %}
{% block contenido %}
    <div class="container">
        <div class="row">
            <div class="col-12">
                <nav aria-label="breadcrumb">
                  <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="{{url_for('actor.index')}}">Actores</a></li>
                        <li class="breadcrumb-item active" aria-current="page">Modificar</li>
                  </ol>
                </nav>
            </div>
        </div>
        <h1>Modificar actor</h1>
        <div class="row">
            <div class="col-12">
                <form action="{{url_for('actor.modificar', id=data.actor.act_i_id)}}" method="post" class="formulario-general">
                    <div class="row">
                        <div class="col-3">
                            <div class="form-floating">
                                <input type="text" class="form-control" id="act_v_nombre" name="act_v_nombre" placeholder="Nombre" value="{{data.actor.act_v_nombre}}">
                                <label for="act_v_nombre">Nombre</label>
                            </div>
                        </div>
                        <div class="col-3">
                            <div class="form-floating">
                                <input type="text" class="form-control" id="act_v_apellido" name="act_v_apellido" placeholder="Apellido" value="{{data.actor.act_v_apellido}}">
                                <label for="act_v_apellido">Apellido</label>
                            </div>
                        </div>
                    </div>

                    <div class="row">
                        <div class="offset-5 col-2">
                            <button class="btn btn-gen">Enviar</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}
{% block scripts %}
<script src="{{ url_for('static', filename='js/formulario_general.js')}}"></script>
{% endblock %}