app/ciudad/models.py
from app.db import db, ma


class Ciudad(db.Model):
    ciu_i_id = db.Column(db.Integer, primary_key=True)
    ciu_v_nombre = db.Column(db.String(50), nullable=False)


class CiudadSchema(ma.SQLAlchemyAutoSchema):
    class Meta:
        model = Ciudad
        fields = ["ciu_i_id", "ciu_v_nombre"]


def get_ciudades():
    ciudades = Ciudad.query.all()
    ciudad_schema = CiudadSchema()
    ciudades = [ciudad_schema.dump(ciudad) for ciudad in ciudades]
    return ciudades


def crear_ciudad(nombre):
    ciudad = Ciudad(ciu_v_nombre=nombre)
    db.session.add(ciudad)
    db.session.commit()
    ciudad_schema = CiudadSchema()
    return ciudad_schema.dump(ciudad)


def eliminar_ciudad(id):
    ciudad = Ciudad.query.filter_by(ciu_i_id=id).first()
    print(ciudad)
    if ciudad != None:
        Ciudad.query.filter_by(ciu_i_id=id).delete()
        db.session.commit()
        return True
    else:
        return False


def modificar_ciudad(id, nombre):
    ciudad = Ciudad.query.filter_by(ciu_i_id=id).first()
    if ciudad != None:
        ciudad.ciu_v_nombre = nombre
        db.session.commit()
        ciudad_schema = CiudadSchema()
        return ciudad_schema.dump(ciudad)
    return None

def ciudad_por_id(id):
    ciudad = Ciudad.query.filter_by(ciu_i_id=id).first()
    if ciudad != None:
        ciudad_schema = CiudadSchema()
        return ciudad_schema.dump(ciudad)
    return None

app/ciudad/views.py
from http import HTTPStatus
from flask import Blueprint, request, render_template, url_for, redirect
from app.ciudad.models import crear_ciudad, get_ciudades, eliminar_ciudad, modificar_ciudad, ciudad_por_id
from app.cine.models import obtener_cines_por_ciudad
import copy
from flask_login import login_required

RESPONSE_BODY_DEFAULT = {"message": "", "data": [], "errors": []}
ciudad = Blueprint("ciudad", __name__, url_prefix="/ciudad")

@ciudad.route("/template", methods=["GET"])
@login_required
def template():
    ciudades = get_ciudades()
    return render_template('ciudad/index.html', ciudades = ciudades)

@ciudad.route("/agregar", methods=["POST","GET"])
@login_required
def agregar():
    response_body = copy.deepcopy(RESPONSE_BODY_DEFAULT)
    status_code = HTTPStatus.OK
    if request.method == "POST":
        if not "ciu_v_nombre" in request.json: 
            response_body["errors"].append("Campo nombre es requerido")
            status_code = HTTPStatus.BAD_REQUEST
            return response_body, status_code

        ciu_v_nombre = request.json["ciu_v_nombre"]

        if ciu_v_nombre == "":
            response_body["errors"].append("Campo nombre es requerido")
            status_code = HTTPStatus.BAD_REQUEST
            return response_body, status_code
        else:
            ciudad = crear_ciudad(ciu_v_nombre)
            response_body["data"] = {"ciudad": ciudad, "redirect": url_for('ciudad.template')}
            response_body["message"] = "Ciudad creada correctamente"
        return response_body, status_code
    else:
        return render_template('ciudad/agregar.html')

@ciudad.route("/editar/<id_ciudad>", methods=["POST","GET"])
@login_required
def editar(id_ciudad):
    response_body = copy.deepcopy(RESPONSE_BODY_DEFAULT)
    status_code = HTTPStatus.OK
    if request.method == "POST":
        if not "ciu_v_nombre" in request.json: 
            response_body["errors"].append("Campo nombre es requerido")
            status_code = HTTPStatus.BAD_REQUEST
            return response_body, status_code

        ciu_v_nombre = request.json["ciu_v_nombre"]
        if ciu_v_nombre == "":
            response_body["errors"].append("Campo nombre es requerido")
            status_code = HTTPStatus.BAD_REQUEST
            return response_body, status_code
        else:
            ciudad = modificar_ciudad(id_ciudad, ciu_v_nombre)
            response_body["data"] = {"ciudad": ciudad, "redirect": url_for('ciudad.template')}
            response_body["message"] = "Ciudad editada correctamente"
        return response_body, status_code
    else:
        ciudad = ciudad_por_id(id_ciudad)
        return render_template('ciudad/editar.html', ciudad = ciudad)

@ciudad.route("/quitar/<id_ciudad>", methods=["GET"])
@login_required
def quitar(id_ciudad):
    response_body = copy.deepcopy(RESPONSE_BODY_DEFAULT)
    status_code = HTTPStatus.OK
    if len(obtener_cines_por_ciudad(id_ciudad)) == 0:
        if eliminar_ciudad(id_ciudad):
            response_body["data"] = {"ciudad": ciudad, "redirect": url_for('ciudad.template')}
            response_body["message"] = "Ciudad eliminada correctamente"
        else:
            response_body["errors"].append("La ciudad no existe")
            status_code = HTTPStatus.BAD_REQUEST
    else:
        response_body["errors"].append("La ciudad tiene datos relacionados")
        status_code = HTTPStatus.BAD_REQUEST

    return redirect(url_for('ciudad.template'))

@ciudad.route("/", methods=["GET"])
def index():
    response_body = copy.deepcopy(RESPONSE_BODY_DEFAULT)
    status_code = HTTPStatus.OK
    ciudades = get_ciudades()
    response_body["message"] = "Ciudades consultadas correctamente!"
    response_body["data"] = ciudades
    return response_body, status_code

@ciudad.route("/crear", methods=["POST"])
def crear():
    response_body = copy.deepcopy(RESPONSE_BODY_DEFAULT)
    status_code = HTTPStatus.OK
    ciu_v_nombre = request.json["ciu_v_nombre"]

    if ciu_v_nombre != "" and ciu_v_nombre != None:
        ciudad = crear_ciudad(ciu_v_nombre)

        response_body["message"] = "Ciudad creada correctamente!"
        response_body["data"] = ciudad
    else:
        response_body["errors"].append("Nombre vacio")
        status_code = HTTPStatus.BAD_REQUEST

    return response_body, status_code


@ciudad.route("/modificar", methods=["PUT"])
def modificar():
    response_body = copy.deepcopy(RESPONSE_BODY_DEFAULT)
    status_code = HTTPStatus.OK

    id = request.json["ciu_i_id"]
    nombre = request.json["ciu_v_nombre"]
    if id != "" and nombre != "" and id != None and nombre != None:
        ciudad_mod = modificar_ciudad(id, nombre)
        if ciudad_mod != None:
            response_body["message"] = "Ciudad modificada correctamente!"
            response_body["data"] = ciudad_mod
        else:
            response_body["message"] = "Error al modificar ciudad"
            response_body["errors"].append("Error al modificar ciudad")
            status_code = HTTPStatus.BAD_REQUEST
    else:
        response_body["message"] = "Error al modificar ciudad"
        response_body["errors"].append("Nombre vacio")
        response_body["errors"].append("Id vacio")
        status_code = HTTPStatus.BAD_REQUEST

    return response_body, status_code


@ciudad.route("/eliminar", methods=["DELETE"])
def eliminar():
    response_body = copy.deepcopy(RESPONSE_BODY_DEFAULT)
    status_code = HTTPStatus.OK

    id = request.json["ciu_i_id"]

    if id != None and id != "":
        #FALTA VERIFICAR QUE LA CIUDAD NO ESTE RELACIONADA CON OTRAS TABLAS.
        if len(obtener_cines_por_ciudad(id)) == 0:

            if eliminar_ciudad(id):
                response_body["message"] = "Ciudad eliminada correctamente!"
            else:
                response_body["message"] = "Error no se encuentra la ciudad"
                response_body["errors"].append("Error no se encuentra la ciudad")
                status_code = HTTPStatus.BAD_REQUEST
        else:
            response_body["message"] = "Error tiene datos relacionados"
            response_body["errors"].append("Error al eliminar ciudad")
            status_code = HTTPStatus.BAD_REQUEST
    else:
        response_body["message"] = "Error al eliminar ciudad"
        response_body["errors"].append("Error al eliminar ciudad")
        status_code = HTTPStatus.BAD_REQUEST

    return response_body, status_code

app/templates/ciudad/agregar.html
{% extends "baseLogueado.html" %}
{% block title %} Peliculas {% endblock %}
{% block head %}
    {{ super() }}
{% endblock %}
{% block contenido %}
    <div class="container">
        <div class="row">
            <div class="col-12">
                <nav aria-label="breadcrumb">
                  <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="{{url_for('ciudad.template')}}">Ciudades</a></li>
                        <li class="breadcrumb-item active" aria-current="page">Agregar</li>
                  </ol>
                </nav>
            </div>
        </div>
        <h1>Agregar Ciudades</h1>
        <div class="row">
            <div class="col-12">
                <form action="{{url_for('ciudad.agregar')}}" method="post" class="formulario-general">
                    <div class="row">
                        <div class="col-3">
                            <div class="form-floating">
                                <input type="text" class="form-control" id="ciu_v_nombre" name="ciu_v_nombre" placeholder="Nombre">
                                <label for="ciu_v_nombre">Nombre</label>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="offset-5 col-2">
                            <button class="btn btn-gen">Enviar</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}
{% block scripts %}
<script src="{{ url_for('static', filename='js/formulario_general.js')}}"></script>
{% endblock %}

app/templates/ciudad/editar.html
{% extends "baseLogueado.html" %}
{% block title %} Peliculas {% endblock %}
{% block head %}
    {{ super() }}
{% endblock %}
{% block contenido %}
    <div class="container">
        <div class="row">
            <div class="col-12">
                <nav aria-label="breadcrumb">
                  <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="{{url_for('ciudad.template')}}">Ciudades</a></li>
                        <li class="breadcrumb-item active" aria-current="page">Editar</li>
                  </ol>
                </nav>
            </div>
        </div>
        <h1>Editar Ciudades</h1>
        <div class="row">
            <div class="col-12">
                <form action="{{url_for('ciudad.editar', id_ciudad=ciudad.ciu_i_id)}}" method="post" class="formulario-general">
                    <div class="row">
                        <div class="col-3">
                            <div class="form-floating">
                                <input type="text" class="form-control" id="ciu_v_nombre" name="ciu_v_nombre" placeholder="Nombre" value="{{ciudad.ciu_v_nombre}}">
                                <label for="ciu_v_nombre">Nombre</label>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="offset-5 col-2">
                            <button class="btn btn-gen">Enviar</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}
{% block scripts %}
<script src="{{ url_for('static', filename='js/formulario_general.js')}}"></script>
{% endblock %}

app/templates/ciudad/index.html
{% extends "baseLogueado.html" %}
{% block title %} Ciudades {% endblock %}
{% block head %}
    {{ super() }}
{% endblock %}
{% block contenido %}
    <div class="container">
        <div class="row">
            <div class="col-12">
                <nav aria-label="breadcrumb">
                  <ol class="breadcrumb">
                    <li class="breadcrumb-item active" aria-current="page">Ciudades</li>
                  </ol>
                </nav>
            </div>
        </div>
        <div class="row">
            <div class="offset-9 col-3 text-end">
                <a class="btn btn-gen" href="{{url_for('ciudad.agregar')}}">Agregar Ciudad</a>
            </div>
        </div>
        <div class="row">
            <table class="table">
                <thead>
                    <tr>
                      <th scope="col">Nombre</th>
                      <th colspan="2" scope="col">Opciones</th>
                    </tr>
                  </thead>
                <tbody>
                {% for ciudad in ciudades %}
                    <tr>
                        <th scope="row">{{ciudad.ciu_v_nombre}}</th>
                        <td><a href="{{url_for('ciudad.editar', id_ciudad=ciudad.ciu_i_id)}}"  class="a-rosa"><i class="far fa-edit"></i></td></a>
                        <td><a href="{{url_for('ciudad.quitar', id_ciudad=ciudad.ciu_i_id)}}" class="a-rosa eliminar" data-msj="esta ciudad"><i class="fas fa-trash-alt"></i></a></td>
                    </tr>
                
                {% endfor %}
                </tbody>
            </table>
        </div>

    </div>
{% endblock %}
{% block scripts %}
<script src="{{ url_for('static', filename='js/lista_general.js')}}"></script>
{% endblock %}