app/sala/models.py
from flask_sqlalchemy import model
from marshmallow import Schema, fields

from app.cine.models import Cine, CineSchema
from app.db import db, ma

class Sala(db.Model):
    sal_i_id = db.Column(db.Integer, primary_key=True)
    sal_i_numero = db.Column(db.SMALLINT, nullable=False)
    sal_t_sillas = db.Column(db.Text, nullable=False)
    sal_fk_cin_i = db.Column(db.Integer, db.ForeignKey("cine.cin_i_id"))

class SalaSchema(ma.SQLAlchemyAutoSchema):
    class Meta:
        model = Sala
        fields = ["sal_i_id", "sal_i_numero", "sal_t_sillas", "sal_fk_cin_i"]


def get_salas_con_cine():
    dupla_sala_cine = db.session.query(Sala,Cine) \
        .filter(Cine.cin_i_id==Sala.sal_fk_cin_i)\
        .order_by(Cine.cin_v_nombre.asc()) \
        .all()

    sala_schema = SalaSchema()
    cine_schema = CineSchema()
    dupla_sala_cine = [(sala_schema.dump(sala),cine_schema.dump(cine)) for (sala,cine) in dupla_sala_cine]
    return dupla_sala_cine

def get_salas():
    salas = Sala.query.all()
    sala_schema = SalaSchema()
    salas = [sala_schema.dump(sala) for sala in salas]
    return salas

def crear_sala(num_sillas, texto, fk_cine):
    sala = Sala(sal_i_numero=num_sillas, sal_t_sillas=texto, sal_fk_cin_i=fk_cine)
    db.session.add(sala)
    db.session.commit()
    sala_schema = SalaSchema()
    return sala_schema.dump(sala)

def eliminar_sala(id):
    sala = Sala.query.filter_by(sal_i_id=id).first()
    if sala != None:
        Sala.query.filter_by(sal_i_id=id).delete()
        db.session.commit()
        return True
    else:
        return False

def modificar_sala(id, num_sillas, texto, cine):
    sala = Sala.query.filter_by(sal_i_id=id).first()
    if sala != None:
        sala.sal_i_numero = num_sillas
        sala.sal_t_sillas = texto
        sala.sal_fk_cin_i = cine
        db.session.commit()
        sala_schema = SalaSchema()
        return sala_schema.dump(sala)
    return None

def obtener_sala_por_id(id):
    sala = Sala.query.filter_by(sal_i_id=id).first()
    if sala != None:
        sala_schema = SalaSchema()
        return sala_schema.dump(sala)
    else:
        return None

app/sala/views.py
from http import HTTPStatus
from flask import Blueprint, request, render_template, url_for
from flask_login import login_required
from werkzeug.utils import redirect

from app.cine.models import get_cines
from app.sala.models import crear_sala, get_salas, eliminar_sala, modificar_sala, get_salas_con_cine, \
    obtener_sala_por_id
import copy
import json

RESPONSE_BODY_DEFAULT = {"message": "", "data": [], "errors": []}
sala = Blueprint("sala", __name__, url_prefix="/sala")

@sala.route("/template", methods=["GET"])
@login_required
def template():
    dupla_sala_cine = get_salas_con_cine()

    data = {
        "sala_cine":dupla_sala_cine
    }

    return render_template('salas/index.html', data = data)


@sala.route("/agregar", methods=["GET","POST"])
@login_required
def agregar():
    response_body = copy.deepcopy(RESPONSE_BODY_DEFAULT)
    status_code = HTTPStatus.OK
    if request.method == "POST":
        sal_i_numero = request.json["sal_i_numero"]
        sal_t_sillas = request.json["sal_t_sillas"]
        sal_fk_cin_i = request.json["sal_fk_cin_i"]

        if sal_i_numero != "" and sal_i_numero != None:
            if sal_t_sillas != "" and sal_t_sillas != None:
                if sal_fk_cin_i != "" and sal_fk_cin_i != None:
                    sala = crear_sala(sal_i_numero, sal_t_sillas, sal_fk_cin_i)

                    response_body["message"] = "Sala creada correctamente!"
                    response_body["data"] = {"sala": sala, "redirect": url_for("sala.template")}

                else:
                    response_body["errors"].append("Cine sin seleccionar")
                    status_code = HTTPStatus.BAD_REQUEST
            else:
                response_body["errors"].append("Sillas vacias")
                status_code = HTTPStatus.BAD_REQUEST
        else:
            response_body["errors"].append("Numero de sillas vacio")
            status_code = HTTPStatus.BAD_REQUEST

        return response_body, status_code
    else:
        cines = get_cines()
        data = {
            "cines" : cines
        }
        return render_template('salas/agregar.html', data = data)

@sala.route("/editar/<int:id>", methods=["GET","POST"])
@login_required
def editar(id):
    response_body = copy.deepcopy(RESPONSE_BODY_DEFAULT)
    status_code = HTTPStatus.OK
    if request.method == "POST":
        sal_i_numero = request.json["sal_i_numero"]
        sal_t_sillas = request.json["sal_t_sillas"]
        sal_fk_cin_i = request.json["sal_fk_cin_i"]

        if sal_i_numero != "" and sal_i_numero != None:
            if sal_t_sillas != "" and sal_t_sillas != None:
                if sal_fk_cin_i != "" and sal_fk_cin_i != None:
                    sala = modificar_sala(id, sal_i_numero, sal_t_sillas, sal_fk_cin_i)

                    response_body["message"] = "Sala modificada correctamente!"
                    response_body["data"] = {"sala": sala, "redirect": url_for("sala.template")}

                else:
                    response_body["errors"].append("Cine sin seleccionar")
                    status_code = HTTPStatus.BAD_REQUEST
            else:
                response_body["errors"].append("Sillas vacias")
                status_code = HTTPStatus.BAD_REQUEST
        else:
            response_body["errors"].append("Numero de sillas vacio")
            status_code = HTTPStatus.BAD_REQUEST

        return response_body, status_code
    else:
        cines = get_cines()
        sala = obtener_sala_por_id(id)
        silla_obj = json.loads(sala["sal_t_sillas"])
        sala["sillas"] = silla_obj
        data = {
            "cines" : cines,
            "sala": sala
        }



        return render_template('salas/modificar.html', data = data)


@sala.route("/borrar/<int:id>", methods=["GET"])
@login_required
def borrar(id):
    response_body = copy.deepcopy(RESPONSE_BODY_DEFAULT)
    status_code = HTTPStatus.OK

    sal_i_id = id

    if sal_i_id != None and sal_i_id != "":
        if eliminar_sala(id):
            return redirect(url_for('sala.template'))
        else:
            response_body["message"] = "No existe la sala"
            response_body["errors"].append("Error al eliminar la sala")
            status_code = HTTPStatus.BAD_REQUEST
    else:
        response_body["message"] = "ID vacio"
        response_body["errors"].append("Error al eliminar la sala")
        status_code = HTTPStatus.BAD_REQUEST

    return response_body, status_code


@sala.route("/", methods=["GET"])
def index():
    response_body = copy.deepcopy(RESPONSE_BODY_DEFAULT)
    status_code = HTTPStatus.OK
    salas = get_salas()
    response_body["message"] = "Salas consultadas correctamente!"
    response_body["data"] = salas
    return response_body, status_code




@sala.route("/crear", methods=["POST"])
def crear():
    response_body = copy.deepcopy(RESPONSE_BODY_DEFAULT)
    status_code = HTTPStatus.OK
    sal_i_numero = request.json["sal_i_numero"]
    sal_t_sillas = request.json["sal_t_sillas"]
    sal_fk_cin_i = request.json["sal_fk_cin_i"]

    if sal_i_numero != "" and sal_i_numero != None:
        if sal_t_sillas != "" and sal_t_sillas != None:
            if sal_fk_cin_i != "" and sal_fk_cin_i != None:
                sala = crear_sala(sal_i_numero, sal_t_sillas, sal_fk_cin_i)

                response_body["message"] = "Ciudad creada correctamente!"
                response_body["data"] = sala
            else:
                response_body["errors"].append("FK vacia")
                status_code = HTTPStatus.BAD_REQUEST
        else:
            response_body["errors"].append("Texto vacio")
            status_code = HTTPStatus.BAD_REQUEST
    else:
        response_body["errors"].append("Numero de sillas vacio")
        status_code = HTTPStatus.BAD_REQUEST
    
    return response_body, status_code

@sala.route("/modificar", methods=["PUT"])
def modificar():
    response_body = copy.deepcopy(RESPONSE_BODY_DEFAULT)
    status_code = HTTPStatus.OK
    
    sal_i_id = request.json["sal_i_id"]
    sal_i_numero = request.json["sal_i_numero"]
    sal_t_sillas = request.json["sal_t_sillas"]
    sal_fk_cin_i = request.json["sal_fk_cin_i"]

    if sal_i_id != "" and sal_i_id != None:
        if sal_i_numero != "" and sal_i_numero != None:
            if sal_t_sillas != "" and sal_t_sillas != None:
                if sal_fk_cin_i != "" and sal_fk_cin_i != None:
                    sala_mod = modificar_sala(sal_i_id, sal_i_numero, sal_t_sillas, )
                    if sala_mod != None:
                        response_body["message"] = "Sala modificada correctamente!"
                        response_body["data"] = sala_mod
                    else:
                        response_body["message"] = "La sala no existe"
                        response_body["errors"].append("Error al modificar sala")
                        status_code = HTTPStatus.BAD_REQUEST
                else:
                    response_body["message"] = "Cine vacio"
                    response_body["errors"].append("Error al modificar ciudad")
                    status_code = HTTPStatus.BAD_REQUEST
            else:
                response_body["message"] = "Texto vacio"
                response_body["errors"].append("Error al modificar ciudad")
                status_code = HTTPStatus.BAD_REQUEST
        else:
            response_body["message"] = "Numero de sillas vacio"
            response_body["errors"].append("Error al modificar ciudad")
            status_code = HTTPStatus.BAD_REQUEST 
    else:
        response_body["message"] = "ID vacio"
        response_body["errors"].append("Error al modificar ciudad")
        status_code = HTTPStatus.BAD_REQUEST 
    
    return response_body, status_code

@sala.route("/eliminar", methods=["DELETE"])
def eliminar():
    response_body = copy.deepcopy(RESPONSE_BODY_DEFAULT)
    status_code = HTTPStatus.OK

    sal_i_id = request.json["sal_i_id"]

    if sal_i_id != None and sal_i_id != "":
        if eliminar_sala(id):
            response_body["message"] = "Sala eliminada correctamente!"
        else:
            response_body["message"] = "No existe la sala"
            response_body["errors"].append("Error al eliminar la sala")
            status_code = HTTPStatus.BAD_REQUEST
    else:
        response_body["message"] = "ID vacio"
        response_body["errors"].append("Error al eliminar la sala")
        status_code = HTTPStatus.BAD_REQUEST
    
    return response_body, status_code

app/templates/salas/agregar.html
{% extends "baseLogueado.html" %}
{% block title %} Sala {% endblock %}
{% block head %}
    {{ super() }}
{% endblock %}
{% block contenido %}
    <div class="container_sala">
        <div class="row">
            <div class="col-12">
                <nav aria-label="breadcrumb">
                  <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="{{url_for('sala.index')}}">Salas</a></li>
                        <li class="breadcrumb-item active" aria-current="page">Agregar</li>
                  </ol>
                </nav>
            </div>
        </div>
        <h1>Agregar sala</h1>
        <div class="row">
            <div class="col-12">
                <form action="{{url_for('sala.agregar')}}" method="post" class="formulario-general">
                    <div class="row">
                        <div class="col-3">
                            <div class="form-floating">
                                <input type="text" class="form-control" id="sal_i_numero" name="sal_i_numero" placeholder="Numero sala">
                                <label for="sal_i_numero">Numero sala</label>
                            </div>
                        </div>
                        <div class="col-3">
                            <div class="form-floating">
                                <select class="form-control form-select" id="sal_fk_cin_i" name="sal_fk_cin_i" required="" >
                                    <option selected value="">Seleccione uno</option>
                                    {% for cine in data.cines %}
                                        <option value="{{ cine.cin_i_id }}">{{cine.cin_v_nombre}}</option>
                                    {% endfor %}
                                 </select>
                                <label for="sal_fk_cin_i">Cine</label>
                            </div>
                        </div>
                        <div class="col-3">
                            <div class="row align-items-center" style="margin-bottom: 1.5em;">
                                <div class="col-md-4 text-right"><label for="num_cols">Columnas</label></div>
                                <div class="col-md-2 text-center">
                                    <a href="#" id="menos_col" class="a-gris"><i class="far fa-minus-square"></i></a>
                                </div>
                                <div class="col-md-4 text-center">
                                    <input type="number" min="1" class="form-control nums" name="num_cols" id="num_cols" value="0">
                                </div>
                                <div class="col-md-2 text-center">
                                    <a href="#" id="mas_col"  class="a-rosa"><i class="far fa-plus-square"></i></a>
                                </div>
                            </div>
                        </div>

                        <div class="col-3">
                            <div class="row align-items-center" style="margin-bottom: 1.5em;">
                                <div class="col-md-4 text-right"><label for="num_filas">Filas</label></div>
                                <div class="col-md-2 text-center">
                                    <a href="#" id="menos_fil" class="a-gris"><i class="far fa-minus-square"></i></a>
                                </div>
                                <div class="col-md-4 text-center">
                                    <input type="number" min="1" class="form-control nums" name="num_filas" id="num_filas" value="0">
                                </div>
                                <div class="col-md-2 text-center">
                                    <a href="#" id="mas_fil"  class="a-rosa"><i class="far fa-plus-square"></i></a>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-12">
                            <div class="cont_grilla">
                                <div id="grilla">

                                </div>
                            </div>
                        </div>
                    </div>
                    <input type="hidden" name="sal_t_sillas" id="sal_t_sillas" value="">
                    <div class="row">
                        <div class="offset-5 col-2">
                            <button class="btn btn-gen">Enviar</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}
{% block scripts %}
<script src="{{ url_for('static', filename='js/formulario_general.js')}}"></script>
<script src="{{ url_for('static', filename='js/formulario_salas.js')}}"></script>
{% endblock %}

app/templates/salas/index.html
{% extends "baseLogueado.html" %}
{% block title %} Sala {% endblock %}
{% block head %}
    {{ super() }}
{% endblock %}
{% block contenido %}
    <div class="container">
        <div class="row">
            <div class="col-12">
                <nav aria-label="breadcrumb">
                  <ol class="breadcrumb">
                    <li class="breadcrumb-item active" aria-current="page">Salas</li>
                  </ol>
                </nav>
            </div>
        </div>
        <div class="row">
            <div class="offset-9 col-3 text-end">
                <a class="btn btn-gen" href="{{url_for('sala.agregar')}}">Agregar sala</a>
            </div>
        </div>

        <table class="table table-hover table-striped">
            <thead>
                <tr>
                    <th scope="col">Num. Sala</th>
                    <th scope="col">Cine</th>
                    <th scope="col">Editar</th>
                    <th scope="col">Eliminar</th>
                </tr>
            </thead>
            <tbody>
                {% for (sala,cine) in data.sala_cine %}
                <tr>
                    <td>{{sala.sal_i_numero}}</td>
                    <td>{{cine.cin_v_nombre}}</td>
                    <td><a href="{{url_for('sala.editar', id=sala.sal_i_id)}}" class="a-rosa"><i class="far fa-edit"></i></a></td>
                    <td><a href="{{url_for('sala.borrar', id=sala.sal_i_id)}}" class="a-rosa eliminar" data-msj="esta sala"><i class="fas fa-trash-alt"></i></a></td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}
{% block scripts %}
<script src="{{ url_for('static', filename='js/lista_general.js')}}"></script>
{% endblock %}

app/templates/salas/modificar.html
{% extends "baseLogueado.html" %}
{% block title %} Sala {% endblock %}
{% block head %}
    {{ super() }}
{% endblock %}
{% block contenido %}
    <div class="container_sala">
        <div class="row">
            <div class="col-12">
                <nav aria-label="breadcrumb">
                  <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="{{url_for('sala.index')}}">Salas</a></li>
                        <li class="breadcrumb-item active" aria-current="page">Modificar</li>
                  </ol>
                </nav>
            </div>
        </div>
        <h1>Modificar sala</h1>
        <div class="row">
            <div class="col-12">
                <form action="{{url_for('sala.editar', id=data.sala.sal_i_id)}}" method="post" class="formulario-general">
                    <div class="row">
                        <div class="col-3">
                            <div class="form-floating">
                                <input type="text" class="form-control" id="sal_i_numero" name="sal_i_numero" placeholder="Numero sala" value="{{data.sala.sal_i_numero}}">
                                <label for="sal_i_numero">Numero sala</label>
                            </div>
                        </div>
                        <div class="col-3">
                            <div class="form-floating">
                                <select class="form-control form-select" id="sal_fk_cin_i" name="sal_fk_cin_i" required="" >
                                    <option selected value="">Seleccione uno</option>
                                    {% for cine in data.cines %}
                                        <option value="{{ cine.cin_i_id }}" {% if(data.sala.sal_fk_cin_i == cine.cin_i_id) %} selected {% endif %}>{{cine.cin_v_nombre}}</option>
                                    {% endfor %}
                                 </select>
                                <label for="sal_fk_cin_i">Cine</label>
                            </div>
                        </div>
                        <div class="col-3">
                            <div class="row align-items-center" style="margin-bottom: 1.5em;">
                                <div class="col-md-4 text-right"><label for="num_cols">Columnas</label></div>
                                <div class="col-md-2 text-center">
                                    <a href="#" id="menos_col" class="a-gris"><i class="far fa-minus-square"></i></a>
                                </div>
                                <div class="col-md-4 text-center">
                                    <input type="number" min="1" class="form-control nums" name="num_cols" id="num_cols" value="{{data.sala.sillas[0]|length}}">
                                </div>
                                <div class="col-md-2 text-center">
                                    <a href="#" id="mas_col"  class="a-rosa"><i class="far fa-plus-square"></i></a>
                                </div>
                            </div>
                        </div>

                        <div class="col-3">
                            <div class="row align-items-center" style="margin-bottom: 1.5em;">
                                <div class="col-md-4 text-right"><label for="num_filas">Filas</label></div>
                                <div class="col-md-2 text-center">
                                    <a href="#" id="menos_fil" class="a-gris"><i class="far fa-minus-square"></i></a>
                                </div>
                                <div class="col-md-4 text-center">
                                    <input type="number" min="1" class="form-control nums" name="num_filas" id="num_filas" value="{{data.sala.sillas|length}}">
                                </div>
                                <div class="col-md-2 text-center">
                                    <a href="#" id="mas_fil"  class="a-rosa"><i class="far fa-plus-square"></i></a>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-12">
                            <div class="cont_grilla">
                                <div id="grilla">
                                </div>
                            </div>
                        </div>
                    </div>
                    <input type="hidden" name="sal_t_sillas" id="sal_t_sillas" value="{{data.sala.sal_t_sillas}}">
                    <div class="row">
                        <div class="offset-5 col-2">
                            <button class="btn btn-gen">Enviar</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}
{% block scripts %}
<script src="{{ url_for('static', filename='js/formulario_general.js')}}"></script>
<script src="{{ url_for('static', filename='js/formulario_salas.js')}}"></script>
{% endblock %}